name: Run CCXT Trading Bot

on:
  schedule:
    - cron: '*/12 * * * *'  # Runs every 15 minutes
  workflow_dispatch:  # Allows manual start

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        run: python bot.py

      # ✅ Auto-restart using GitHub API
      - name: Trigger Next Run
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/main.yml/dispatches \
          -d '{"ref":"main"}'
          
